// src/components/ui/Header.svelte
<script>
  import { vsmDataStore } from '../../stores/vsmDataStore.svelte.js'
  import { vsmIOStore } from '../../stores/vsmIOStore.svelte.js'
  import { exportAsJson, exportAsPng, exportAsPdf } from '../../utils/export/index.js'

  let isEditingName = $state(false)
  let tempName = $state(vsmDataStore.name)
  let fileInputRef = $state(null)

  function handleNameClick() {
    tempName = vsmDataStore.name
    isEditingName = true
  }

  function handleNameSubmit() {
    if (tempName.trim()) {
      vsmDataStore.updateMapName(tempName.trim())
    }
    isEditingName = false
  }

  function handleNameKeyDown(e) {
    if (e.key === 'Enter') {
      handleNameSubmit()
    } else if (e.key === 'Escape') {
      isEditingName = false
    }
  }

  function handleExportJson() {
    const json = vsmIOStore.exportToJson()
    exportAsJson(json, `${vsmDataStore.name || 'vsm'}.json`)
  }

  async function handleExportPng() {
    const canvas = document.querySelector('.svelte-flow')
    if (!canvas) return

    try {
      await exportAsPng(canvas, `${vsmDataStore.name || 'vsm'}.png`)
    } catch (err) {
      if (import.meta.env.DEV) {
        console.error('Failed to export PNG:', err)
      }
    }
  }

  async function handleExportPdf() {
    const canvas = document.querySelector('.svelte-flow')
    if (!canvas) return

    try {
      await exportAsPdf(canvas, `${vsmDataStore.name || 'vsm'}.pdf`)
    } catch (err) {
      if (import.meta.env.DEV) {
        console.error('Failed to export PDF:', err)
      }
    }
  }

  function handleImport() {
    fileInputRef?.click()
  }

  function handleFileChange(e) {
    const file = e.target.files?.[0]
    if (!file) return

    const reader = new FileReader()
    reader.onload = (event) => {
      const result = vsmIOStore.importFromJson(event.target.result)
      if (!result) {
        alert('Failed to import file. Please check the format.')
      }
    }
    reader.onerror = () => {
      alert('Failed to read file.')
    }
    reader.readAsText(file)
    e.target.value = ''
  }

  function handleNewMap() {
    if (confirm('Create a new map? This will clear the current map.')) {
      vsmDataStore.clearMap()
    }
  }
</script>

<header class="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between">
  <div class="flex items-center gap-4">
    <div class="flex items-center gap-2">
      <span class="text-xl">🗺️</span>
      <span class="font-semibold text-gray-700">VSM Workshop</span>
    </div>
    <div class="h-6 w-px bg-gray-300"></div>
    {#if isEditingName}
      <input
        type="text"
        bind:value={tempName}
        onblur={handleNameSubmit}
        onkeydown={handleNameKeyDown}
        class="px-2 py-1 border border-blue-500 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
        data-testid="map-name-input"
      />
    {:else}
      <button
        onclick={handleNameClick}
        class="text-lg font-medium text-gray-800 hover:text-blue-600 transition-colors"
        data-testid="map-name"
      >
        {vsmDataStore.name}
      </button>
    {/if}
  </div>

  <div class="flex items-center gap-2">
    <button
      onclick={handleNewMap}
      class="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors"
      data-testid="new-map-button"
    >
      New Map
    </button>
    <button
      onclick={handleImport}
      class="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors"
      data-testid="import-button"
    >
      Import
    </button>
    <div class="relative group">
      <button
        class="px-3 py-1.5 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
        data-testid="export-button"
      >
        Export ▾
      </button>
      <div class="absolute right-0 mt-1 w-40 bg-white border border-gray-200 rounded shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-50">
        <button
          onclick={handleExportJson}
          class="w-full px-4 py-2 text-left text-sm hover:bg-gray-100"
          data-testid="export-json"
        >
          Export as JSON
        </button>
        <button
          onclick={handleExportPng}
          class="w-full px-4 py-2 text-left text-sm hover:bg-gray-100"
          data-testid="export-png"
        >
          Export as PNG
        </button>
        <button
          onclick={handleExportPdf}
          class="w-full px-4 py-2 text-left text-sm hover:bg-gray-100"
          data-testid="export-pdf"
        >
          Export as PDF
        </button>
      </div>
    </div>
    <input
      bind:this={fileInputRef}
      type="file"
      accept=".json"
      onchange={handleFileChange}
      class="hidden"
    />
  </div>
</header>

// src/components/ui/Header.jsx
import { useState, useCallback } from 'react'
import PropTypes from 'prop-types'
import { useVsmStore } from '../../stores/vsmStore'
import useFileOperations from '../../hooks/useFileOperations'

function Header() {
  const { name, updateMapName } = useVsmStore()
  const [isEditingName, setIsEditingName] = useState(false)
  const [tempName, setTempName] = useState(name)

  const {
    fileInputRef,
    handleExportJson,
    handleExportPng,
    handleExportPdf,
    handleImport,
    handleFileChange,
    handleNewMap,
  } = useFileOperations()

  const handleNameClick = useCallback(() => {
    setTempName(name)
    setIsEditingName(true)
  }, [name])

  const handleNameSubmit = useCallback(() => {
    if (tempName.trim()) {
      updateMapName(tempName.trim())
    }
    setIsEditingName(false)
  }, [tempName, updateMapName])

  const handleNameKeyDown = useCallback(
    (e) => {
      if (e.key === 'Enter') {
        handleNameSubmit()
      } else if (e.key === 'Escape') {
        setIsEditingName(false)
      }
    },
    [handleNameSubmit]
  )

  return (
    <header className="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between">
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2">
          <span className="text-xl">🗺️</span>
          <span className="font-semibold text-gray-700">VSM Workshop</span>
        </div>
        <div className="h-6 w-px bg-gray-300" />
        {isEditingName ? (
          <input
            type="text"
            value={tempName}
            onChange={(e) => setTempName(e.target.value)}
            onBlur={handleNameSubmit}
            onKeyDown={handleNameKeyDown}
            className="px-2 py-1 border border-blue-500 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            autoFocus
            data-testid="map-name-input"
          />
        ) : (
          <button
            onClick={handleNameClick}
            className="text-lg font-medium text-gray-800 hover:text-blue-600 transition-colors"
            data-testid="map-name"
          >
            {name}
          </button>
        )}
      </div>

      <div className="flex items-center gap-2">
        <button
          onClick={handleNewMap}
          className="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors"
          data-testid="new-map-button"
        >
          New Map
        </button>
        <button
          onClick={handleImport}
          className="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded transition-colors"
          data-testid="import-button"
        >
          Import
        </button>
        <div className="relative group">
          <button
            className="px-3 py-1.5 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
            data-testid="export-button"
          >
            Export ▾
          </button>
          <div className="absolute right-0 mt-1 w-40 bg-white border border-gray-200 rounded shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-50">
            <button
              onClick={handleExportJson}
              className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100"
              data-testid="export-json"
            >
              Export as JSON
            </button>
            <button
              onClick={handleExportPng}
              className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100"
              data-testid="export-png"
            >
              Export as PNG
            </button>
            <button
              onClick={handleExportPdf}
              className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100"
              data-testid="export-pdf"
            >
              Export as PDF
            </button>
          </div>
        </div>
        <input
          ref={fileInputRef}
          type="file"
          accept=".json"
          onChange={handleFileChange}
          className="hidden"
        />
      </div>
    </header>
  )
}

export default Header
